steps:
# use node 8.9.1 this is the recommended version for building the typed rest client
- task: NodeTool@0
  inputs:
    versionSpec: "8.9.1"

# install dependencies
- task: CmdLine@1
  inputs:
    filename: "npm"
    arguments: "install"

# build
- task: CmdLine@1
  inputs:
    filename: "npm"
    arguments: "run build"

# test using node 8.9.1
- task: CmdLine@1
  inputs:
    filename: "npm"
    arguments: "run test"

# test using node 4.8.6
- task: NodeTool@0
  inputs:
    versionSpec: "4.8.6"

- task: CmdLine@1
  inputs:
    filename: "npm"
    arguments: "run test"

# test using node 6.12.0
- task: NodeTool@0
  inputs:
    versionSpec: "6.12.0"

- task: CmdLine@1
  inputs:
    filename: "npm"
    arguments: "run test"

# publish build artifacts to drop folder so we can use them for release
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "_build"
    ArtifactName: "drop"
    ArtifactType: "Container"
